version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./app
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    volumes:
      - ./app/:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev.dev

#  django_api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#
#    env_file: .env.dev
#    depends_on:
#      pgdb:
#        condition: service_healthy

#  django:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./app/:/usr/src/app/
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.env.dev

#    depends_on:
#      - pgdb

#
#  pgdb:
#    image: postgres:13-alpine
#    restart: always
#    container_name: pgdb
#    environment:
#      - POSTGRES_DB=postgresdb
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - pgdata:/var/lib/postgresql/data/
#    ports:
#      - "5452:5432"
#
#volumes:
#  pgdata:








