# Generated by Django 4.1.6 on 2023-02-10 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('update_id', models.BigIntegerField(null=True)),
                ('chat_id', models.BigIntegerField(null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('verification_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('verification_True', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
