# Generated by Django 4.1.6 on 2023-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='user',
        ),
        migrations.AddField(
            model_name='tguser',
            name='user_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
